repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first # to ensure docstrings are at the beginning of file.
      - id: trailing-whitespace # to remove trailing whitespace.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: check-ast # Simply check whether the files parse as valid python
      - id: check-toml # This hook checks toml files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
        args: [--allow-multiple-documents]
      - id: check-added-large-files # Prevent giant files from being committed (500kB)
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: detect-private-key # Detects the presence of private keys
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: name-tests-test

-   repo: https://github.com/codespell-project/codespell
    rev: 'v2.2.4'
    hooks:
      - id: codespell


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports, --implicit-reexport]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: ^dist/
        args: ["--line-length=170"]


-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
    -   id: autoflake

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
     - id: isort
       name: isort (python)
       args: ["--profile", "black"]


-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=170


- repo: https://github.com/PyCQA/bandit
  rev: 1.6.3
  hooks:
    - id: bandit


- repo: https://github.com/pycqa/pylint
  rev: pylint-2.7.4
  hooks:
    - id: pylint


- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.2.1  # Replace with the version you want to use
  hooks:
    - id: python-safety-dependencies-check
      additional_dependencies: [safety]
